Adding first draft of buildwget and buildflex (buildflex works on Linux but not yet on OS X).  Refactored other build scripts.

diff --git a/install_prerequisites/buildflex b/install_prerequisites/buildflex
--- a/install_prerequisites/buildflex
+++ b/install_prerequisites/buildflex
@@ -1,8 +1,9 @@
 #!/bin/bash
 #
-# buildmpich
+# buildflex
 #
-# -- This script downloads and installs the MPICH library (http://www.mpich.org).
+# -- This script downloads and installs the flex lexical analyzer
+#    (http://www.flex.org).
 #
 # OpenCoarrays is distributed under the OSI-approved BSD 3-clause License:
 # Copyright (c) 2015, Sourcery, Inc.
@@ -32,24 +33,14 @@
 # ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
 # POSSIBILITY OF SUCH DAMAGE.
 
-# Default to installing MPICH 3.1.4 if no version specified in the first
-# command-line argument
-if [[ $1 == 'default' ]]; then
-  version=3.1.4
-else
-  version=$1 
-fi
-
 cmd=`basename $0` 
-src=mpich-$version
-
 usage()
 {
     echo ""
-    echo " $cmd - Bash script for building MPICH from source"
+    echo " $cmd - Bash script for building flex from source"
     echo ""
     echo " Usage (optional arguments in square brackets): "
-    echo "      $cmd <version-number> <install-path> <number-of-threads>"
+    echo "      $cmd <version-number> [<installation-path> <number-of-threads>]"
     echo " or   $cmd [options] "
     echo ""
     echo " Options:"
@@ -59,25 +50,75 @@ usage()
     echo " Example usage:"
     echo ""
     echo "   $cmd default"
-    echo "   $cmd 3.1.4 /opt/mpich/3.1.4 4"
+    echo "   $cmd 2.5.39"
+    echo "   $cmd 2.5.39 /opt/flex/2.5.39 4"
     echo "   $cmd -v" 
     echo "   $cmd --help"
     echo ""
-    echo " Note: For a list of available MPICH versions, visit"
-    echo " http://www.mpich.org/static/downloads/"
+    echo " Note: For a list of available flex versions, visit"
+    echo " http://www.flex.org/files/"
     echo ""
     exit 1
 }
 
+# Default to installing flex if no version specified in the first
+# command-line argument
+if [[ $1 == 'default' ]]; then
+  version=2.5.39
+else
+  version=$1 
+fi
+
+build_path=${PWD}/flex-$version-build
+
+# Default to installing in the present working directory if no install path is specified:
+if [ -z $2 ]; then
+  install_path=$build_path
+else
+  install_path=$2
+fi
+
+# Default to 2 threads if no specified thread count:
+if [ -z $3 ]; then
+  num_threads=1
+else
+  num_threads=$3
+fi
+
 check_prerequisites()
 {
+  unamestr=`uname`
+  if [[ "$unamestr" == 'Darwin' ]]; then
+    if [ -f /usr/bin/gcc ]; then
+      CC=/usr/bin/gcc
+    else
+      echo "Missing /usr/bin/gcc, which must exist and be an Apple LLVM version."
+      exit 1
+    fi
+    if [ -f /usr/bin/g++ ]; then
+      CXX=/usr/bin/g++
+    else
+      echo "Missing /usr/bin/g++, which must exist and be an Apple LLVM version."
+      exit 1
+    fi
+  else
+    # If this is not OS X, default to the user-specified compiler.
+    # If there is no user-specified compiler, use whatever the 
+    # GNU compilers are in the path.
+    if [ -z $CC ]; then
+      CC=gcc
+    fi
+    if [ -z $CXX ]; then
+      CXX=g++
+    fi
+  fi
+
   # Verify that 'wget' is in the path.
   if ! type wget > /dev/null; then
     echo 
     echo "$cmd requires 'wget'.  Please ensure that it is installed and in your path.  Aborting." 
     exit 1
   fi
-  # Verify that 'make' is in the path.
   if ! type make > /dev/null; then
     echo 
     echo "$cmd requires 'make'.  Please ensure that it is installed and in your path.  Aborting." 
@@ -85,59 +126,33 @@ check_prerequisites()
   fi
 }
 
-# Download wvet if the tar ball is not already in the present working directory
+# Download flex if the tar ball is not already in the present working directory
 download()
 {
-  if [ ! -f "$src.tar.gz" ]; then
-    echo "Downloading $src.tar.gz" 
-    wget http://www.mpich.org/static/downloads/$version/$src.tar.gz
-  fi  
+  echo "Download flex-$version (.*gz.xf ."
+  if [ ! -f "flex-$version.tar.gz" ]; then
+    echo "Downloading flex $version tar ball"
+    wget http://sourceforge.net/projects/flex/files/flex-$version.tar.xz
+  fi
 }
 
-# Unpack CMake if the unpacked tar ball is not in the present working directory
+# Unpack flex if the unpacked tar ball is not in the present working directory
 unpack()
 {
-  if [ ! -d "$src" ]; then
-    tar xvzf $src.tar.gz 
-  fi  
+  if [ ! -d "flex-$version" ]; then
+    echo "Unpacking into flex-$version"
+    tar xf flex-$version.tar.xz 
+  fi
 }
-
-# Default to compiling with the GNU compilers if the environment 
-# variables CC, FC, and CXX, are empty:
-if [ -z "$CC" ]; then
-  CC=gcc
-fi
-if [ -z "$FC" ]; then
-  FC=gfortran
-fi
-if [ -z "$CXX" ]; then
-  CXX=g++
-fi
-
-# Default to installing in the current directory if no path is provided
-# in the second command-line argument
-if [ -z $2 ]; then
-  install_path=${PWD}mpich-$version-installation
-else
-  install_path=$2
-fi
-
-# Default to building with 2 threads if no thread count is specified
-# in the third command-line argument
-if [ -z $3 ]; then
-  num_threads=2
-else
-  num_threads=$3
-fi
-
 
 # Make the build directory, configure, and build
 build()
 {
-   mkdir -p $src\-build &&
-   cd $src\-build &&
-   CC=$CC FC=$FC CXX=$CXX ../$src/configure --prefix=$install_path && 
-   CC=$CC FC=$FC CXX=$CXX make -j $num_threads 
+  echo "Building flex $version"
+  mkdir -p $build_path &&
+  cd $build_path &&
+  CC=$CC CXX=$CXX ../flex-$version/configure --prefix=$install_path &&
+  make -j $num_threads
 }
 
 if [ $# == 0 ]; then
@@ -149,7 +164,7 @@ elif [[ $1 == '--help' || $1 == '-h' ]]; then
 elif [[ $1 == '-v' || $1 == '-V' || $1 == '--version' ]]; then
   # Print script copyright if invoked with -v, -V, or --version argument
   echo ""
-  echo "MPICH Build Script"
+  echo "flex Build Script"
   echo "Copyright (C) 2015 Sourcery, Inc."
   echo "Copyright (C) 2015 Sourcery Institute"
   echo ""
@@ -159,15 +174,17 @@ elif [[ $1 == '-v' || $1 == '-V' || $1 == '--version' ]]; then
   echo "http://www.sourceryinstitute.org/license.html"
   echo ""
 else
-  # Download and build MPICH
+  # Download, unpack, and build flex
   time \
   {
-      check_prerequisites &&
-      download &&
-      unpack&&
-      build $version $install_path $num_threads
+    check_prerequisites &&
+    download &&
+    unpack  &&
+    CC=$CC CXX=$CXX build $version $install_path $num_threads
   } >&1 | tee build.log
+  echo ""
   echo "Check build.log for results.  If the build was successful, type"
-  echo "'cd $src-build && make install' (or 'cd $src-build && sudo make install') "
+  echo "'cd $build_path && make install' (or 'cd $build_path && sudo make install')"
   echo "to complete the installation."
+  echo ""
 fi
diff --git a/install_prerequisites/buildwget b/install_prerequisites/buildwget
--- a/install_prerequisites/buildwget
+++ b/install_prerequisites/buildwget
@@ -1,8 +1,9 @@
 #!/bin/bash
 #
-# buildmpich
+# buildwget
 #
-# -- This script downloads and installs the MPICH library (http://www.mpich.org).
+# -- This script downloads and installs the GNU wget file retrieval package
+#    (https://www.gnu.org/software/wget/)
 #
 # OpenCoarrays is distributed under the OSI-approved BSD 3-clause License:
 # Copyright (c) 2015, Sourcery, Inc.
@@ -32,52 +33,72 @@
 # ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
 # POSSIBILITY OF SUCH DAMAGE.
 
-# Default to installing MPICH 3.1.4 if no version specified in the first
-# command-line argument
-if [[ $1 == 'default' ]]; then
-  version=3.1.4
-else
-  version=$1 
-fi
-
 cmd=`basename $0` 
-src=mpich-$version
-
 usage()
 {
     echo ""
-    echo " $cmd - Bash script for building MPICH from source"
+    echo " $cmd - Bash script for building wget from source"
     echo ""
     echo " Usage (optional arguments in square brackets): "
-    echo "      $cmd <version-number> <install-path> <number-of-threads>"
+    echo "      $cmd <version-number> [<installation-path> <number-of-threads>]"
     echo " or   $cmd [options] "
     echo ""
     echo " Options:"
     echo "   --help, -h           Show this help message"
-    echo "   --version, -v, -V    Report version and copyright information"
+    echo "   --version, -v, -V    Show this help message"
     echo ""
     echo " Example usage:"
     echo ""
     echo "   $cmd default"
-    echo "   $cmd 3.1.4 /opt/mpich/3.1.4 4"
-    echo "   $cmd -v" 
+    echo "   $cmd 1.16.3"
+    echo "   $cmd 1.16.3 /opt/ftp/1.16.3 4"
     echo "   $cmd --help"
     echo ""
-    echo " Note: For a list of available MPICH versions, visit"
-    echo " http://www.mpich.org/static/downloads/"
+    echo " Note: For a list of available wget versions, visit"
+    echo " http://ftp.gnu.org/gnu/wget/?C=M;O=D"
     echo ""
     exit 1
 }
 
+# Default to installing wget 1.16.3 if no version specified in the first
+# command-line argument
+if [[ $1 == 'default' ]]; then
+  version=1.16.3
+else
+  version=$1 
+fi
+
+build_path=${PWD}/wget-$version-build
+
+# Default to installing in the present working directory if no install path is specified:
+if [ -z $2 ]; then
+  install_path=$build_path
+else
+  install_path=$2
+fi
+
+# Default to 2 threads if no specified thread count:
+if [ -z $3 ]; then
+  num_threads=1
+else
+  num_threads=$3
+fi
+
 check_prerequisites()
 {
-  # Verify that 'wget' is in the path.
-  if ! type wget > /dev/null; then
+  # If there are no user-specified compilers in the path, default to gcc/g++.
+  if [ -z $CC ]; then
+    CC=gcc
+  fi  
+  if [ -z $CXX ]; then
+    CXX=g++
+  fi 
+  # Verify that 'ftp' is is in the path.
+  if ! type ftp > /dev/null; then
     echo 
-    echo "$cmd requires 'wget'.  Please ensure that it is installed and in your path.  Aborting." 
+    echo "$cmd requires 'ftp'.  Please ensure that it is installed and in your path.  Aborting." 
     exit 1
   fi
-  # Verify that 'make' is in the path.
   if ! type make > /dev/null; then
     echo 
     echo "$cmd requires 'make'.  Please ensure that it is installed and in your path.  Aborting." 
@@ -85,59 +106,39 @@ check_prerequisites()
   fi
 }
 
-# Download wvet if the tar ball is not already in the present working directory
+# Download wget if the tar ball is not already in the present working directory
 download()
 {
-  if [ ! -f "$src.tar.gz" ]; then
-    echo "Downloading $src.tar.gz" 
-    wget http://www.mpich.org/static/downloads/$version/$src.tar.gz
-  fi  
+  if [ ! -f "wget-$version.tar.xz" ]; then
+    echo "Downloading wget-$version.tar.xz"
+    ftp -n ftp://ftp.gnu.org<<END_SCRIPT
+    cd gnu
+    cd wget
+    get wget-1.16.3.tar.xz
+    quit
+END_SCRIPT
+  else 
+    echo "Found wget-$version.tar.xz in the current directory.  Skipping download"
+  fi
 }
 
-# Unpack CMake if the unpacked tar ball is not in the present working directory
+# Unpack wget if the unpacked tar ball is not in the present working directory
 unpack()
 {
-  if [ ! -d "$src" ]; then
-    tar xvzf $src.tar.gz 
-  fi  
+  if [ ! -d "wget-$version" ]; then
+    echo "Unpacking wget-$version.tar.xz"
+    tar xf wget-$version.tar.xz 
+  fi
 }
-
-# Default to compiling with the GNU compilers if the environment 
-# variables CC, FC, and CXX, are empty:
-if [ -z "$CC" ]; then
-  CC=gcc
-fi
-if [ -z "$FC" ]; then
-  FC=gfortran
-fi
-if [ -z "$CXX" ]; then
-  CXX=g++
-fi
-
-# Default to installing in the current directory if no path is provided
-# in the second command-line argument
-if [ -z $2 ]; then
-  install_path=${PWD}mpich-$version-installation
-else
-  install_path=$2
-fi
-
-# Default to building with 2 threads if no thread count is specified
-# in the third command-line argument
-if [ -z $3 ]; then
-  num_threads=2
-else
-  num_threads=$3
-fi
-
 
 # Make the build directory, configure, and build
 build()
 {
-   mkdir -p $src\-build &&
-   cd $src\-build &&
-   CC=$CC FC=$FC CXX=$CXX ../$src/configure --prefix=$install_path && 
-   CC=$CC FC=$FC CXX=$CXX make -j $num_threads 
+  echo "Building wget"
+  mkdir -p $build_path &&
+  cd $build_path &&
+  ../wget-$version/configure --prefix=$install_path #&&
+  CC=$CC CXX=$CXX make -j $num_threads
 }
 
 if [ $# == 0 ]; then
@@ -149,7 +150,7 @@ elif [[ $1 == '--help' || $1 == '-h' ]]; then
 elif [[ $1 == '-v' || $1 == '-V' || $1 == '--version' ]]; then
   # Print script copyright if invoked with -v, -V, or --version argument
   echo ""
-  echo "MPICH Build Script"
+  echo "wget Build Script"
   echo "Copyright (C) 2015 Sourcery, Inc."
   echo "Copyright (C) 2015 Sourcery Institute"
   echo ""
@@ -159,15 +160,17 @@ elif [[ $1 == '-v' || $1 == '-V' || $1 == '--version' ]]; then
   echo "http://www.sourceryinstitute.org/license.html"
   echo ""
 else
-  # Download and build MPICH
+  # Download, unpack, and build CMake
   time \
   {
-      check_prerequisites &&
-      download &&
-      unpack&&
-      build $version $install_path $num_threads
+    check_prerequisites &&
+    download &&
+    unpack  &&
+    CC=$CC CXX=$CXX build $version $install_path $num_threads
   } >&1 | tee build.log
+  echo ""
   echo "Check build.log for results.  If the build was successful, type"
-  echo "'cd $src-build && make install' (or 'cd $src-build && sudo make install') "
-  echo "to complete the installation."
+  echo "'cd wget-$version-build && make install' (or 'cd wget-$version-build && sudo make install')"
+  echo "to complete the installation, after which wget will be in the 'bin' subdirectory of $install_path" 
+  echo ""
 fi
