Add 1.x build/install improvements back to master
Signed-off-by: Izaak Beekman <zbeekman@gmail.com>

diff --git a/install_prerequisites/build b/install_prerequisites/build
--- a/install_prerequisites/build
+++ b/install_prerequisites/build
@@ -80,13 +80,16 @@ set_default_version()
   # denominator because, for licensing reasons, OS X only has bash 3 by default.)
   # See http://stackoverflow.com/questions/1494178/how-to-define-hash-tables-in-bash
   package_version=( 
-    "cmake:3.3.2"
+    "cmake:3.4.0"
     "gcc:trunk"
     "mpich:3.1.4"
     "wget:1.16.3"
-    "flex:2.6.0rc1"
+    "flex:2.6.0"
+    "bison:3.0.4"
     "pkg-config:0.28"
     "make:4.1"
+    "m4:1.4.17"
+    "subversion:1.9.2"
     "_unknown:0" 
   )
   for package in "${package_version[@]}" ; do
@@ -132,20 +135,18 @@ fi
 # Interpret the third command-line argument, if present, as the installation path.
 # Otherwise, install in a subdirectory of the present working directory.
 default_install_path=${PWD}/$package_to_build-$version_to_build-installation
-if [[ -z $3 || $3 == "--query" ]]; then
+if [[ -z $3 || $3 == "--query-path" ]]; then
   install_path=$default_install_path
 else
-  install_path=$2
+  install_path=$3
 fi
-
-build_path=${PWD}/$package_to_build-$version_to_build-build
 
 # Interpret the fourth command-line argument, if present, as the number of threads for 'make'.
 # Otherwise, default to single-threaded 'make'.
 if [ -z $4 ]; then
   num_threads=1
 else
-  num_threads=$3
+  num_threads=$4
 fi
 
 
@@ -160,8 +161,11 @@ check_prerequisites()
     "cmake:wget"
     "mpich:wget"
     "flex:wget"
+    "bison:wget"
     "pkg-config:wget"
     "make:ftp"
+    "m4:ftp"
+    "subversion:wget"
     "_unknown:0" 
   )
   for package in "${package_download_mechanism[@]}" ; do
@@ -207,11 +211,14 @@ download_if_necessary()
   package_url_head=( 
     "gcc;svn://gcc.gnu.org/svn/gcc/"
     "wget;ftp.gnu.org:/gnu/wget/"
+    "m4;ftp.gnu.org:/gnu/m4/"
     "pkg-config;http://pkgconfig.freedesktop.org/releases/"
     "mpich;http://www.mpich.org/static/downloads/$version_to_build/"
     "flex;http://sourceforge.net/projects/flex/files/"
     "make;ftp://ftp.gnu.org/gnu/make/"
+    "bison;http://ftp.gnu.org/gnu/bison/"
     "cmake;http://www.cmake.org/files/v$major_minor/"
+    "subversion;http://www.eu.apache.org/dist/subversion/"
     "_unknown;0" 
   )
   for package in "${package_url_head[@]}" ; do
@@ -232,18 +239,23 @@ download_if_necessary()
   if [[ $package_to_build == 'gcc' ]]; then
     if [[ $version_to_build == 'trunk' ]]; then
       gcc_tail='trunk'
+    elif [[ $version_to_build == '--avail' || $version_to_build == '-a' ]]; then
+      gcc_tail='branches'
     else
-    gcc_tail=/branches/$version_to_build
+      gcc_tail=/branches/$version_to_build
     fi
   fi  
   package_url_tail=( 
     "gcc;$gcc_tail"
     "wget;wget-$version_to_build.tar.xz"
+    "m4;m4-$version_to_build.tar.xz"
     "pkg-config;pkg-config-$version_to_build.tar.gz"
     "mpich;mpich-$version_to_build.tar.gz"
     "flex;flex-$version_to_build.tar.xz"
+    "bison;bison-$version_to_build.tar.xz"
     "make;make-$version_to_build.tar.bz2"
     "cmake;cmake-$version_to_build.tar.gz "
+    "subversion;subversion-$version_to_build.tar.gz"
     "_unknown;0" 
   )
   for package in "${package_url_tail[@]}" ; do
@@ -261,18 +273,25 @@ download_if_necessary()
   done
   url="$url_head""$url_tail"
 
-  if [ -f "$url_tail" ]; then
-    echo "Found $url_tail in the current directory.  Skipping download"
-  elif [ -d "$url_tail" ]; then
-    #  This happens with directories downloaded via version control solftware.  
-    #  Cowardly refusing to tackle the complexities of version control in a script.
-    #  Braver solutions might involve "svn cleanup $url_tail && svn update $url_tail"
-    #  or "git pull --rebase".
-    echo "Found $url_tail subdirectory in the present working directory."
-    echo "Please rename or remove it and restart the '$this_script' script."
+  if [ -f $url_tail ] || [ -d $url_tail ]; then
+    echo "Found '$url_tail' in ${PWD}."
+    echo "If it resulted from an incomplete download, building $package_to_build could fail."
+    printf "Would you like to proceed anyway? (y/n)"
+    read proceed
+    if [[ $proceed == "y"  ]]; then
+      printf "y\n"
+    else
+      printf "n\n"
+      printf "Please remove $url_tail and restart the installation to to ensure a fresh download."
+      exit 1
+    fi
   else 
-    if [[ "$fetch" == "svn" || "$fetch" == "cvs" ]]; then
-      args=checkout
+    if [[ "$fetch" == "svn" ]]; then
+      if [[ $version_to_build == '--avail' || $version_to_build == '-a' ]]; then
+        args=ls
+      else
+        args=checkout
+      fi
     elif [[ "$fetch" == "wget" ]]; then
       args=--no-check-certificate
     elif [[ "$fetch" == "ftp" ]]; then
@@ -280,16 +299,34 @@ download_if_necessary()
     elif [[ "$fetch" == "git" ]]; then
       args=clone
     fi
-    printf "Downloading $package_to_build $version_to_build.\n"
+    if [[ $fetch == "svn" || $fetch == "git" ]]; then
+      package_source_directory=$url_tail
+    else 
+      package_source_directory=$package_to_build-$version_to_build 
+    fi
+    printf "Downloading $package_to_build $version_to_build to the following location:\n"
+    printf "$download_path/$package_source_directory \n"
     printf "Download command: $fetch $args $url\n"
-    $fetch $args $url 
+    $fetch $args $url
+    if [[ $version_to_build == '--avail' || $version_to_build == '-a' ]]; then
+      # In this case, args="ls" and the list of available versions has been printed so we can move on.
+      exit 1
+    fi 
+    if [ -f $download_path/$url_tail ] || [ -d $download_path/$url_tail ]; then
+      echo "Download succeeded. $url_tail is in the following location:"
+      echo "$download_path"
+    else
+      echo "Download failed: $url_tail is not in the following, expected location:"
+      echo "$download_path"
+      exit 1
+    fi
   fi
 }
 
 # Unpack pkg-config if the unpacked tar ball is not in the present working directory
 unpack_if_necessary()
 { 
-  if [[ $fetch == "svn" || $fetch == "git" || $fetch == "cvs" ]]; then
+  if [[ $fetch == "svn" || $fetch == "git" ]]; then
     package_source_directory=$url_tail
   else 
     printf "Unpacking $url_tail. \n" 
@@ -302,13 +339,27 @@ unpack_if_necessary()
 # Make the build directory, configure, and build
 build_and_install()
 {
+
+  build_path=${PWD}/$package_to_build-$version_to_build-build &&
   printf "Building $package_to_build $version_to_build.\n" &&
   mkdir -p $build_path &&
-  cd $build_path &&
-  ../$package_source_directory/configure --prefix=$install_path &&
-  CC=$CC CXX=$CXX make -j $num_threads &&
-  printf "Installing $package_to_build in $install_path.\n" &&
-  make install
+  pushd $build_path &&
+  if [[ $package_to_build == "gcc" ]]; then
+    pushd $download_path/$package_source_directory &&  
+    ${PWD}/contrib/download_prerequisites &&
+    popd &&
+    echo "Configuring with the following command: " &&
+    echo "$download_path/$package_source_directory/configure  --prefix=$install_path --enable-languages=c,c++,fortran,lto --disable-multilib --disable-werror " &&
+    $download_path/$package_source_directory/configure --prefix=$install_path --enable-languages=c,c++,fortran,lto --disable-multilib --disable-werror &&  
+    make -j $num_threads bootstrap &&
+    make install
+  else
+    $download_path/$package_source_directory/configure --prefix=$install_path &&
+    CC=$CC CXX=$CXX make -j $num_threads &&
+    printf "Installing $package_to_build in $install_path.\n" &&
+    make install
+  fi &&
+  popd
 }
 
 if [ $# == 0 ]; then
@@ -317,9 +368,12 @@ if [ $# == 0 ]; then
 elif [[ $1 == '--help' || $1 == '-h' ]]; then
   # Print usage information if script is invoked with --help or -h argument
   usage | less
-elif [[ $2 == '--default' && $3 == '--query' ]]; then
+elif [[ $2 == '--default' && $3 == '--query-path' ]]; then
   # Print the installation path and exit
   printf "$install_path\n"
+  exit 0
+elif [[ $2 == '--default' && $3 == '--query-version' ]]; then
+  printf "$default_version\n"
   exit 0
 elif [[ $1 == '-v' || $1 == '-V' || $1 == '--version' ]]; then
   # Print script copyright if invoked with -v, -V, or --version argument
@@ -335,17 +389,13 @@ elif [[ $1 == '-v' || $1 == '-V' || $1 == '--version' ]]; then
   echo ""
 else
   # Download, unpack, and build CMake
-  time \
-  {
-    check_prerequisites &&
-    download_if_necessary &&
-    unpack_if_necessary &&
-    CC=$CC CXX=$CXX build_and_install $package_to_build $version_to_build $install_path $num_threads 
-  } >&1 | tee build-$package_to_build.log
-  printf "\n"
-  printf "$this_script: Done. Check for $package_to_build in the installation path $install_path\n"
+  download_path=${PWD}
+  check_prerequisites &&
+  download_if_necessary &&
+  unpack_if_necessary &&
+  CC=$CC CXX=$CXX build_and_install $package_to_build $version_to_build $install_path $num_threads $download_path \
+  >&1 | tee build-$package_to_build.log &&
+  printf "\n" &&
+  printf "$this_script: Done. Check for $package_to_build in the installation path $install_path\n" &&
   printf "\n"
 fi
-
-#printf "'cd $package_to_build-build && make install' (or 'cd $package_to_build-build && sudo make install')\n"
-#printf "to complete the installation, after which $package_to_build will be in the 'bin' subdirectory of $install_path \n"  
