Improve Travis-CI logic

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,6 +1,37 @@
-language: generic
-
+sudo: false
+language: cpp
+os:
+  - linux
+  - osx
+copmpiler:
+  - gcc
+matrix:
+  exclude:
+    - os: osx
+      env: BUILD=Lint
+addons:
+  apt:
+    sources:
+      - ubuntu-toolchain-r-test
+      - george-edison55-precise-backports
+    packages:
+      - gcc-5
+      - gfortran-5
+      - g++-5
+      - cmake-data
+      - cmake
+      - binutils
+cache:
+  apt: true
+  directories:
+    - "$HOME/.cache"
 env:
+  matrix:
+    - BUILD=CodeCoverage
+    - BUILD=Release lMPI=MPICH
+    - BUILD=Release lMPI=OMPI
+    - BUILD=Script
+    - BUILD=Lint
   global:
     - CACHE="$HOME/.local"
     - MPICH_VER="3.1.4"
@@ -9,178 +40,189 @@ env:
     - MPICH_DIR="$HOME/.local/usr/mpich"
     - MPICH_BOT_URL_HEAD="https://github.com/sourceryinstitute/opencoarrays/files/64308/"
     - MPICH_BOT_URL_TAIL="mpich-3.2.yosemite.bottle.1.tar.gz"
-
-matrix:
-  include:
-    - os: osx
-      env:
-        - BUILD_TYPE="CodeCoverage"
-          OSX_PACKAGES="gcc cmake"
-    - os: osx
-      env:
-       - BUILD_TYPE="Release"
-         OSX_PACKAGES="gcc cmake"
-    - os: osx
-      env:
-       - BUILD_TYPE="InstallScript"
-         OSX_PACKAGES="gcc"
-    - os: linux
-      sudo: false
-      env:
-        - BUILD_TYPE="CodeCoverage"
-      cache:
-        directories:
-          - "$CACHE"
-      addons:
-        apt:
-          sources:
-            - george-edison55-precise-backports
-            - ubuntu-toolchain-r-test
-          packages:
-            - gcc-5
-            - gfortran-5
-            - binutils
-            - cmake-data
-            - cmake
-    - os: linux
-      sudo: false
-      env:
-        - BUILD_TYPE="Release"
-      cache:
-        directories:
-          - "$CACHE"
-      addons:
-        apt:
-          sources:
-            - george-edison55-precise-backports
-            - ubuntu-toolchain-r-test
-          packages:
-            - gcc-5
-            - gfortran-5
-            - binutils
-            - cmake-data
-            - cmake
-    - os: linux
-      sudo: false
-      env:
-        - BUILD_TYPE="InstallScript"
-      addons:
-        apt:
-          sources:
-            - ubuntu-toolchain-r-test
-          packages:
-            - gcc-5
-            - gfortran-5
-
 before_install:
-  - |
-    if [[ $TRAVIS ]] && [[ "X$TRAVIS_OS_NAME" = "Xosx" ]]; then
-      export PATH="$PATH:$HOME/Library/Python/2.7/bin"
-    else
-      [[ -d "$CACHE/bin" ]] || mkdir -p "$CACHE/bin"
-      [[ -d "$MPICH_DIR" ]] || mkdir -p "$MPICH_DIR"
-      export PATH="$CACHE/bin:$PATH"
-      export FC=gfortran-5
-      export CC=gcc-5
-      $FC --version
-      $CC --version
-    fi
-
-install:
-  - |
-    if [[ $TRAVIS ]] && [[ "X$TRAVIS_OS_NAME" = "Xosx" ]]; then
-      brew update > /dev/null
-
-      for pkg in $OSX_PACKAGES; do
-        [[ "$(brew ls --versions $pkg)" ]] || brew install --force-bottle $pkg
-        brew outdated $pkg || brew upgrade --force-bottle $pkg
-      done
-      export FC=gfortran-5
-      export CC=gcc-5
-      if ! [[ "$(brew ls --versions mpich)" ]] && [[ "X$BUILD_TYPE" != "XInstallScript" ]]; then
-        wget ${MPICH_BOT_URL_HEAD}${MPICH_BOT_URL_TAIL}
-        brew install --force-bottle ${MPICH_BOT_URL_TAIL}
-        if ! [[ "$(brew ls --versions mpich)" ]]; then
-          brew install --force-bottle mpich
-        fi
-        mpif90 --version
-        mpicc --version
-        cmake --version
-        export FC=mpif90
-        export CC=mpicc
-      elif [[ "X$BUILD_TYPE" = "XInstallScript" ]]; then # uninstall some stuff if present
-        [[ "$(brew ls --versions cmake)" ]] && brew rm cmake || true
-        [[ "$(brew ls --versions mpich)" ]] && brew rm mpich || true
-        [[ "$(brew ls --versions openmpi)" ]] && brew rm openmpi || true
-      fi
-    elif [[ "X$BUILD_TYPE" != "XInstallScript" ]]; then # Ubuntu on Travis-CI, NOT testing install.sh
-      if ! ( [[ -x "$HOME/.local/bin/mpif90" ]] && [[ -x "$HOME/.local/bin/mpicc" ]] ); then
-        # mpich install not cached
-        # could use install_prerequisites/build instead...
-        wget "${MPICH_URL_HEAD}/${MPICH_URL_TAIL}"
-        mv "$MPICH_URL_TAIL" "$MPICH_DIR/.."
-        pushd "$MPICH_DIR/.."
-        tar -xzvf "$MPICH_URL_TAIL"
-        cd "${MPICH_URL_TAIL%.tar.gz}"
-        ./configure --prefix="$MPICH_DIR"
-        make -j 4
-        make install
-        popd
-        for f in "$MPICH_DIR/bin/"*; do
-          if [[ -x "$f" ]]; then
-            ln -fs "$f" "$HOME/.local/bin/${f##*/}" && "${f##*/}" --version
-          fi
-        done
-      fi
-      mpif90 --version
-      mpicc --version
-      cmake --version
-      export FC=mpif90
-      export CC=mpicc
-    fi
-
+  - uname
+  - if [[ "$(uname)" = "Darwin" ]]; then brew update > /dev/null; fi
 script:
-  - |
-    if [[ "X$BUILD_TYPE" = "XInstallScript" ]]; then
-      export FC=gfortran-5
-      export CC=gcc-5
-      [[ -d "$HOME/opt" ]] || mkdir "$HOME/opt"
-      [[ -d "$HOME/bin" ]] || mkdir "$HOME/bin"
-      ln -fs "$(which gfortran-5)" "$HOME/bin/gfortran"
-      ln -fs "$(which gcc-5)" "$HOME/bin/gcc"
-      ln -fs "$(which g++-5)" "$HOME/bin/g++"
-      export PATH="$PATH:$HOME/bin"
-      yes | ./install.sh $HOME/opt/opencoarrays 4 > install.log &
-      install_sh_PID=$!
-      echo "install.log will be displayed after success or failure"
-      while ps -p $install_sh_PID > /dev/null; do
-        echo "Still working on installing opencoarrays and dependencies"
-        sleep 300 # prevent Travis-CI abort due to inactivity and excessive logging
-      done
-    else
-      mkdir cmake-build
-      cd cmake-build
-      cmake -DCMAKE_INSTALL_PREFIX:PATH="$HOME/OpenCoarrays" -DCMAKE_BUILD_TYPE="$BUILD_TYPE" ..
-      make -j 4
-      ctest --verbose
-      make install
-      cd ..
-    fi
+  - gcc --version
+  - gcc-5 --version
+  - gfortran-5 --version
+  - g++ --version
+  - g++-5 --version
+  - ls -l $(which gcc)
+  - ls -l $(which gcc-5)
+  - ls -l $(which gfortran-5)
+# matrix:
+#   include:
+#     - os: osx
+#       env:
+#         - BUILD_TYPE="CodeCoverage"
+#           OSX_PACKAGES="gcc cmake"
+#     - os: osx
+#       env:
+#        - BUILD_TYPE="Release"
+#          OSX_PACKAGES="gcc cmake"
+#     - os: osx
+#       env:
+#        - BUILD_TYPE="InstallScript"
+#          OSX_PACKAGES="gcc"
+#     - os: linux
+#       sudo: false
+#       env:
+#         - BUILD_TYPE="CodeCoverage"
+#       cache:
+#         directories:
+#           - "$CACHE"
+#       addons:
+#         apt:
+#           sources:
+#             - george-edison55-precise-backports
+#             - ubuntu-toolchain-r-test
+#           packages:
+#             - gcc-5
+#             - gfortran-5
+#             - binutils
+#             - cmake-data
+#             - cmake
+#     - os: linux
+#       sudo: false
+#       env:
+#         - BUILD_TYPE="Release"
+#       cache:
+#         directories:
+#           - "$CACHE"
+#       addons:
+#         apt:
+#           sources:
+#             - george-edison55-precise-backports
+#             - ubuntu-toolchain-r-test
+#           packages:
+#             - gcc-5
+#             - gfortran-5
+#             - binutils
+#             - cmake-data
+#             - cmake
+#     - os: linux
+#       sudo: false
+#       env:
+#         - BUILD_TYPE="InstallScript"
+#       addons:
+#         apt:
+#           sources:
+#             - ubuntu-toolchain-r-test
+#           packages:
+#             - gcc-5
+#             - gfortran-5
 
-after_success:
-  - find . -name '*.gcno' -print
-  - gcov-5 --version
-  - bash <(curl -s https://codecov.io/bash) -x $(which gcov-5)
-  - cat install.log || true
+# before_install:
+#   - |
+#     if [[ $TRAVIS ]] && [[ "X$TRAVIS_OS_NAME" = "Xosx" ]]; then
+#       export PATH="$PATH:$HOME/Library/Python/2.7/bin"
+#     else
+#       [[ -d "$CACHE/bin" ]] || mkdir -p "$CACHE/bin"
+#       [[ -d "$MPICH_DIR" ]] || mkdir -p "$MPICH_DIR"
+#       export PATH="$CACHE/bin:$PATH"
+#       export FC=gfortran-5
+#       export CC=gcc-5
+#       $FC --version
+#       $CC --version
+#     fi
 
-after_failure:
-  - cat install.log || true
+# install:
+#   - |
+#     if [[ $TRAVIS ]] && [[ "X$TRAVIS_OS_NAME" = "Xosx" ]]; then
+#       brew update > /dev/null
 
-notifications:
-  webhooks:
-    urls:
-      - https://webhooks.gitter.im/e/93dbafbdf76c1732a623
-      - https://webhooks.gitter.im/e/935231573bf1b9f2fe40
-    on_success: change  # options: [always|never|change]
-    on_failure: always
-    on_start: always
+#       for pkg in $OSX_PACKAGES; do
+#         [[ "$(brew ls --versions $pkg)" ]] || brew install --force-bottle $pkg
+#         brew outdated $pkg || brew upgrade --force-bottle $pkg
+#       done
+#       export FC=gfortran-5
+#       export CC=gcc-5
+#       if ! [[ "$(brew ls --versions mpich)" ]] && [[ "X$BUILD_TYPE" != "XInstallScript" ]]; then
+#         wget ${MPICH_BOT_URL_HEAD}${MPICH_BOT_URL_TAIL}
+#         brew install --force-bottle ${MPICH_BOT_URL_TAIL}
+#         if ! [[ "$(brew ls --versions mpich)" ]]; then
+#           brew install --force-bottle mpich
+#         fi
+#         mpif90 --version
+#         mpicc --version
+#         cmake --version
+#         export FC=mpif90
+#         export CC=mpicc
+#       elif [[ "X$BUILD_TYPE" = "XInstallScript" ]]; then # uninstall some stuff if present
+#         [[ "$(brew ls --versions cmake)" ]] && brew rm cmake || true
+#         [[ "$(brew ls --versions mpich)" ]] && brew rm mpich || true
+#         [[ "$(brew ls --versions openmpi)" ]] && brew rm openmpi || true
+#       fi
+#     elif [[ "X$BUILD_TYPE" != "XInstallScript" ]]; then # Ubuntu on Travis-CI, NOT testing install.sh
+#       if ! ( [[ -x "$HOME/.local/bin/mpif90" ]] && [[ -x "$HOME/.local/bin/mpicc" ]] ); then
+#         # mpich install not cached
+#         # could use install_prerequisites/build instead...
+#         wget "${MPICH_URL_HEAD}/${MPICH_URL_TAIL}"
+#         mv "$MPICH_URL_TAIL" "$MPICH_DIR/.."
+#         pushd "$MPICH_DIR/.."
+#         tar -xzvf "$MPICH_URL_TAIL"
+#         cd "${MPICH_URL_TAIL%.tar.gz}"
+#         ./configure --prefix="$MPICH_DIR"
+#         make -j 4
+#         make install
+#         popd
+#         for f in "$MPICH_DIR/bin/"*; do
+#           if [[ -x "$f" ]]; then
+#             ln -fs "$f" "$HOME/.local/bin/${f##*/}" && "${f##*/}" --version
+#           fi
+#         done
+#       fi
+#       mpif90 --version
+#       mpicc --version
+#       cmake --version
+#       export FC=mpif90
+#       export CC=mpicc
+#     fi
+
+# script:
+#   - |
+#     if [[ "X$BUILD_TYPE" = "XInstallScript" ]]; then
+#       export FC=gfortran-5
+#       export CC=gcc-5
+#       [[ -d "$HOME/opt" ]] || mkdir "$HOME/opt"
+#       [[ -d "$HOME/bin" ]] || mkdir "$HOME/bin"
+#       ln -fs "$(which gfortran-5)" "$HOME/bin/gfortran"
+#       ln -fs "$(which gcc-5)" "$HOME/bin/gcc"
+#       ln -fs "$(which g++-5)" "$HOME/bin/g++"
+#       export PATH="$PATH:$HOME/bin"
+#       yes | ./install.sh $HOME/opt/opencoarrays 4 > install.log &
+#       install_sh_PID=$!
+#       echo "install.log will be displayed after success or failure"
+#       while ps -p $install_sh_PID > /dev/null; do
+#         echo "Still working on installing opencoarrays and dependencies"
+#         sleep 300 # prevent Travis-CI abort due to inactivity and excessive logging
+#       done
+#     else
+#       mkdir cmake-build
+#       cd cmake-build
+#       cmake -DCMAKE_INSTALL_PREFIX:PATH="$HOME/OpenCoarrays" -DCMAKE_BUILD_TYPE="$BUILD_TYPE" ..
+#       make -j 4
+#       ctest --verbose
+#       make install
+#       cd ..
+#     fi
+
+# after_success:
+#   - find . -name '*.gcno' -print
+#   - gcov-5 --version
+#   - bash <(curl -s https://codecov.io/bash) -x $(which gcov-5)
+#   - cat install.log || true
+
+# after_failure:
+#   - cat install.log || true
+
+# notifications:
+#   webhooks:
+#     urls:
+#       - https://webhooks.gitter.im/e/93dbafbdf76c1732a623
+#       - https://webhooks.gitter.im/e/935231573bf1b9f2fe40
+#     on_success: change  # options: [always|never|change]
+#     on_failure: always
+#     on_start: always
