Expand Travis-CI matrix & ready GH release uploads
 Configure .travis.yml for GH releases and legibility, and expand the
 test matrix in a much more readable way

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,187 +1,250 @@
+sudo: false # Use fast containerized linux builds
+
 language: generic
 
-env:
-  global:
-    - CACHE="$HOME/.local"
-    - MPICH_VER="3.2"
-    - MPICH_URL_HEAD="http://www.mpich.org/static/downloads/$MPICH_VER"
-    - MPICH_URL_TAIL="mpich-${MPICH_VER}.tar.gz"
-    - MPICH_DIR="$HOME/.local/usr/mpich"
-    - MPICH_BOT_URL_HEAD="https://github.com/sourceryinstitute/opencoarrays/files/303249/"
-    - MPICH_BOT_URL_TAIL="mpich-3.2_1.yosemite.bottle.1.tar.gz"
+os: # Test on both OS X and Linux
+  - linux
+  - osx
 
 matrix:
-  include:
+  exclude: # Don't run the "Lint" build on OS X
     - os: osx
-      env:
-        - BUILD_TYPE="CodeCoverage"
-          OSX_PACKAGES="gcc cmake"
-    - os: osx
-      env:
-       - BUILD_TYPE="Release"
-         OSX_PACKAGES="gcc cmake"
-    - os: osx
-      env:
-       - BUILD_TYPE="InstallScript"
-         OSX_PACKAGES="gcc"
+      env: BUILD=Lint lMPI=NONE
     - os: linux
-      sudo: false
-      env:
-        - BUILD_TYPE="CodeCoverage"
-      cache:
-        directories:
-          - "$CACHE"
-      addons:
-        apt:
-          sources:
-            - george-edison55-precise-backports
-            - ubuntu-toolchain-r-test
-          packages:
-            - gcc-6
-            - gfortran-6
-            - g++-6
-            - binutils
-            - cmake-data
-            - cmake
-    - os: linux
-      sudo: false
-      env:
-        - BUILD_TYPE="Release"
-      cache:
-        directories:
-          - "$CACHE"
-      addons:
-        apt:
-          sources:
-            - george-edison55-precise-backports
-            - ubuntu-toolchain-r-test
-          packages:
-            - gcc-6
-            - gfortran-6
-            - g++-6
-            - binutils
-            - cmake-data
-            - cmake
-    - os: linux
-      sudo: false
-      env:
-        - BUILD_TYPE="InstallScript"
-      addons:
-        apt:
-          sources:
-            - ubuntu-toolchain-r-test
-          packages:
-            - gcc-6
-            - gfortran-6
-            - g++-6
+      env: BUILD=Release lMPI=openmpi
+
+# Deep clone so we can check things with git,
+# C.F. https://github.com/travis-ci/travis-ci/issues/4942
+git:
+  depth: 500
+
+addons: # Packages needed to bootstrap linuxbrew
+  apt:
+    packages:
+      - gawk
+      - build-essential
+      - ruby
+      - curl
+
+cache: # Use caching on linux container builds
+  apt: true
+  directories:
+    - "$HOME/.cache"
+    - "$HOME/.linuxbrew"
+
+env:
+  matrix:
+    - BUILD=CodeCoverage lMPI=mpich
+    - BUILD=Release lMPI=mpich
+    - BUILD=Release lMPI=openmpi
+    - BUILD=Script lMPI=mpich
+    - BUILD=Lint lMPI=NONE
+  # global:
+  #   - CACHE="$HOME/.local"
+  #   - MPICH_VER="3.1.4"
+  #   - MPICH_URL_HEAD="http://www.mpich.org/static/downloads/$MPICH_VER"
+  #   - MPICH_URL_TAIL="mpich-${MPICH_VER}.tar.gz"
+  #   - MPICH_DIR="$HOME/.local/usr/mpich"
+  #   - MPICH_BOT_URL_HEAD="https://github.com/sourceryinstitute/opencoarrays/files/64308/"
+  #   - MPICH_BOT_URL_TAIL="mpich-3.2.yosemite.bottle.1.tar.gz"
 
 before_install:
-  - |
-    set -o errexit
-    if [[ $TRAVIS ]] && [[ "X$TRAVIS_OS_NAME" = "Xosx" ]]; then
-      export PATH="$PATH:$HOME/Library/Python/2.7/bin"
-    else
-      [[ -d "$CACHE/bin" ]] || mkdir -p "$CACHE/bin"
-      [[ -d "$MPICH_DIR" ]] || mkdir -p "$MPICH_DIR"
-      export PATH="$CACHE/bin:$PATH"
-      export FC=gfortran-6
-      export CC=gcc-6
-      export CXX=g++-6
-      $FC --version
-      $CC --version
-      $CXX --version
-    fi
-    set +o errexit
+  - uname
+  - source .travis-scripts/set-env.sh # map travis-ci environment to saner variables
 
 install:
-  - |
-    set -o errexit
-    if [[ $TRAVIS ]] && [[ "X$TRAVIS_OS_NAME" = "Xosx" ]]; then
-      brew update > /dev/null
-
-      for pkg in $OSX_PACKAGES; do
-        [[ "$(brew ls --versions $pkg)" ]] || brew install --force-bottle $pkg
-        brew outdated $pkg || brew upgrade --force-bottle $pkg
-      done
-      export FC=gfortran-6
-      export CC=gcc-6
-      if ! [[ "$(brew ls --versions mpich)" ]] && [[ "X$BUILD_TYPE" != "XInstallScript" ]]; then
-        wget ${MPICH_BOT_URL_HEAD}${MPICH_BOT_URL_TAIL}
-        brew install --force-bottle ${MPICH_BOT_URL_TAIL}
-        if ! [[ "$(brew ls --versions mpich)" ]]; then
-          brew install --force-bottle mpich
-        fi
-        mpif90 --version
-        mpicc --version
-        cmake --version
-        export FC=mpif90
-        export CC=mpicc
-      elif [[ "X$BUILD_TYPE" = "XInstallScript" ]]; then # uninstall some stuff if present
-        [[ "$(brew ls --versions cmake)" ]] && brew rm cmake || true
-        [[ "$(brew ls --versions mpich)" ]] && brew rm mpich || true
-        [[ "$(brew ls --versions openmpi)" ]] && brew rm openmpi || true
-      fi
-    elif [[ "X$BUILD_TYPE" != "XInstallScript" ]]; then # Ubuntu on Travis-CI, NOT testing install.sh
-      if ! ( [[ -x "$HOME/.local/bin/mpif90" ]] && [[ -x "$HOME/.local/bin/mpicc" ]] ); then
-        # mpich install not cached
-        # could use prerequisites/build instead...
-        wget "${MPICH_URL_HEAD}/${MPICH_URL_TAIL}"
-        mv "$MPICH_URL_TAIL" "$MPICH_DIR/.."
-        pushd "$MPICH_DIR/.."
-        tar -xzvf "$MPICH_URL_TAIL"
-        cd "${MPICH_URL_TAIL%.tar.gz}"
-        ./configure --prefix="$MPICH_DIR"
-        make -j 4
-        make install
-        popd
-        for f in "$MPICH_DIR/bin/"*; do
-          if [[ -x "$f" ]]; then
-            ln -fs "$f" "$HOME/.local/bin/${f##*/}"
-          fi
-        done
-      fi
-      mpif90 --version
-      mpicc --version
-      cmake --version
-      export FC=mpif90
-      export CC=mpicc
-    fi
-    set +o errexit
+  - .travis-scripts/install.sh --build=$BUILD --mpi-lib=${lMPI:-mpich}
 
 script:
-  - |
-    set -o errexit
-    if [[ "X$BUILD_TYPE" = "XInstallScript" ]]; then
-      export FC=gfortran-6
-      export CC=gcc-6
-      [[ -d "$HOME/opt" ]] || mkdir "$HOME/opt"
-      [[ -d "$HOME/bin" ]] || mkdir "$HOME/bin"
-      ln -fs "$(which gfortran-6)" "$HOME/bin/gfortran"
-      ln -fs "$(which gcc-6)" "$HOME/bin/gcc"
-      ln -fs "$(which g++-6)" "$HOME/bin/g++"
-      export PATH="$PATH:$HOME/bin"
-      ./install.sh --yes-to-all -i "$HOME/opt/opencoarrays" -j 4 -f "$HOME/bin/gfortran" -c "$HOME/bin/gcc" -C "$HOME/bin/g++"
-    else
-      mkdir cmake-build
-      cd cmake-build
-      cmake -DCMAKE_INSTALL_PREFIX:PATH="$HOME/OpenCoarrays" -DCMAKE_BUILD_TYPE="$BUILD_TYPE" ..
-      make -j 4
-      ctest --verbose
-      make install
-      cd ..
-    fi
-    set +o errexit
+  - .travis-scripts/build.sh --build=$BUILD --lmpi=${lMPI:-mpich}
 
-after_success:
+after_success: # Upload coverage data and dump logs
   - find . -name '*.gcno' -print
-  - gcov-6 --version
-  - bash <(curl -s https://codecov.io/bash) -x $(which gcov-6)
+  - gcov-5 --version
+  - bash <(curl -s https://codecov.io/bash) -x $(which gcov-5)
+  - cat install.log || true
+
+after_failure: # dump logs
+  - cat install.log || true
+
+deploy:
+  provider: releases # Github releases
+  api_key: # encrypted access token `travis encrypt --add deploy.api_key <token>`
+    secure: m41yBJ5RUgT9M992PwZPbeoNmwsEaYDW3+YRsrbutkJdujnQvoxPd8OSLQkFEIGRiwMSCmW5k7N/01j6caDaYO3EbltoWxbTq0Qb58UEuIfs4XpH7dD5uEcs/QALza5Fx/D9n74JBhLjL1SLRYeh4RCAcbSHPkpSq8uy225R/thRRgSB7iNFjQjIqFPAmNKfAlIYVA0Wd2he6+eQ3M5yRgFJNS1kRU4cb3JlBREHAyy+r6/JKMy5NAOVvRio/PJDuNoTgWFehhRlwYYMw7cXArqV4ubIyoZnyfODf9a1m3nId188BuEi5iWpcnWlTacYGuUmH90YHuUx9kXAfBvNT1k/x8mWqGOcpZqstEzC+L34eRpZY9JwUI3nzdwH4+rrFujdVJwt2jIu8JOYAsbJ5died7qxRjBjLIOEevOcF/JVMKhtFvF8PbYcPl8aYofwjN+ouXbZoYhjnKnoiEfEJH1QYw0paGxZFlAVOcRMHF7dXlBbDTBLdz8zuUojaErKUl5ggiRub65ILG66P9t8yd+uTlZXvpdJ7nQE9v6dCQHkIwhtf59CdthhwxFLU69M1Z/2UAJTCmz7KAM7FwMK+NGvRZpwP4d6VBJIRGM8O6ABt10P/Tjt5RHLopA6N64uw+pq5suNOP/pIGCTKZusaxFtCT8tPM/opX2TRVyYe8M=
+  file:
+    - "OpenCoarrays-${TRAVIS_TAG}.tar.gz"
+    - "opencoarrays-${TRAVIS_TAG}-SHA-256.txt"
+  skip_cleanup: true
+  on:
+    tags: true
+    repo: "sourceryinstitute/opencoarrays"
+    condition: ("X$BUILD" = "XScript") && ("X$lMPI" = "XMPICH") && ("XTRAVIS_OS_NAME" = "Xlinux")
+    # Use release assets generated by the "(install) Script" build
 
 notifications:
+  email:
+    on_success: change
+    on_failure: always
   webhooks:
     urls:
       - https://webhooks.gitter.im/e/93dbafbdf76c1732a623
       - https://webhooks.gitter.im/e/935231573bf1b9f2fe40
-    on_success: change  # options: [always|never|change]
+    on_success: always  # options: [always|never|change]
     on_failure: always
     on_start: always
+# matrix:
+#   include:
+#     - os: osx
+#       env:
+#         - BUILD_TYPE="CodeCoverage"
+#           OSX_PACKAGES="gcc cmake"
+#     - os: osx
+#       env:
+#        - BUILD_TYPE="Release"
+#          OSX_PACKAGES="gcc cmake"
+#     - os: osx
+#       env:
+#        - BUILD_TYPE="InstallScript"
+#          OSX_PACKAGES="gcc"
+#     - os: linux
+#       sudo: false
+#       env:
+#         - BUILD_TYPE="CodeCoverage"
+#       cache:
+#         directories:
+#           - "$CACHE"
+#       addons:
+#         apt:
+#           sources:
+#             - george-edison55-precise-backports
+#             - ubuntu-toolchain-r-test
+#           packages:
+#             - gcc-5
+#             - gfortran-5
+#             - binutils
+#             - cmake-data
+#             - cmake
+#     - os: linux
+#       sudo: false
+#       env:
+#         - BUILD_TYPE="Release"
+#       cache:
+#         directories:
+#           - "$CACHE"
+#       addons:
+#         apt:
+#           sources:
+#             - george-edison55-precise-backports
+#             - ubuntu-toolchain-r-test
+#           packages:
+#             - gcc-5
+#             - gfortran-5
+#             - binutils
+#             - cmake-data
+#             - cmake
+#     - os: linux
+#       sudo: false
+#       env:
+#         - BUILD_TYPE="InstallScript"
+#       addons:
+#         apt:
+#           sources:
+#             - ubuntu-toolchain-r-test
+#           packages:
+#             - gcc-5
+#             - gfortran-5
+
+# before_install:
+#   - |
+#     if [[ $TRAVIS ]] && [[ "X$TRAVIS_OS_NAME" = "Xosx" ]]; then
+#       export PATH="$PATH:$HOME/Library/Python/2.7/bin"
+#     else
+#       [[ -d "$CACHE/bin" ]] || mkdir -p "$CACHE/bin"
+#       [[ -d "$MPICH_DIR" ]] || mkdir -p "$MPICH_DIR"
+#       export PATH="$CACHE/bin:$PATH"
+#       export FC=gfortran-5
+#       export CC=gcc-5
+#       $FC --version
+#       $CC --version
+#     fi
+
+# install:
+#   - |
+#     if [[ $TRAVIS ]] && [[ "X$TRAVIS_OS_NAME" = "Xosx" ]]; then
+#       brew update > /dev/null
+
+#       for pkg in $OSX_PACKAGES; do
+#         [[ "$(brew ls --versions $pkg)" ]] || brew install --force-bottle $pkg
+#         brew outdated $pkg || brew upgrade --force-bottle $pkg
+#       done
+#       export FC=gfortran-5
+#       export CC=gcc-5
+#       if ! [[ "$(brew ls --versions mpich)" ]] && [[ "X$BUILD_TYPE" != "XInstallScript" ]]; then
+#         wget ${MPICH_BOT_URL_HEAD}${MPICH_BOT_URL_TAIL}
+#         brew install --force-bottle ${MPICH_BOT_URL_TAIL}
+#         if ! [[ "$(brew ls --versions mpich)" ]]; then
+#           brew install --force-bottle mpich
+#         fi
+#         mpif90 --version
+#         mpicc --version
+#         cmake --version
+#         export FC=mpif90
+#         export CC=mpicc
+#       elif [[ "X$BUILD_TYPE" = "XInstallScript" ]]; then # uninstall some stuff if present
+#         [[ "$(brew ls --versions cmake)" ]] && brew rm cmake || true
+#         [[ "$(brew ls --versions mpich)" ]] && brew rm mpich || true
+#         [[ "$(brew ls --versions openmpi)" ]] && brew rm openmpi || true
+#       fi
+#     elif [[ "X$BUILD_TYPE" != "XInstallScript" ]]; then # Ubuntu on Travis-CI, NOT testing install.sh
+#       if ! ( [[ -x "$HOME/.local/bin/mpif90" ]] && [[ -x "$HOME/.local/bin/mpicc" ]] ); then
+#         # mpich install not cached
+#         # could use install_prerequisites/build instead...
+#         wget "${MPICH_URL_HEAD}/${MPICH_URL_TAIL}"
+#         mv "$MPICH_URL_TAIL" "$MPICH_DIR/.."
+#         pushd "$MPICH_DIR/.."
+#         tar -xzvf "$MPICH_URL_TAIL"
+#         cd "${MPICH_URL_TAIL%.tar.gz}"
+#         ./configure --prefix="$MPICH_DIR"
+#         make -j 4
+#         make install
+#         popd
+#         for f in "$MPICH_DIR/bin/"*; do
+#           if [[ -x "$f" ]]; then
+#             ln -fs "$f" "$HOME/.local/bin/${f##*/}" && "${f##*/}" --version
+#           fi
+#         done
+#       fi
+#       mpif90 --version
+#       mpicc --version
+#       cmake --version
+#       export FC=mpif90
+#       export CC=mpicc
+#     fi
+
+# script:
+#   - |
+#     if [[ "X$BUILD_TYPE" = "XInstallScript" ]]; then
+#       export FC=gfortran-5
+#       export CC=gcc-5
+#       [[ -d "$HOME/opt" ]] || mkdir "$HOME/opt"
+#       [[ -d "$HOME/bin" ]] || mkdir "$HOME/bin"
+#       ln -fs "$(which gfortran-5)" "$HOME/bin/gfortran"
+#       ln -fs "$(which gcc-5)" "$HOME/bin/gcc"
+#       ln -fs "$(which g++-5)" "$HOME/bin/g++"
+#       export PATH="$PATH:$HOME/bin"
+#       yes | ./install.sh $HOME/opt/opencoarrays 4 > install.log &
+#       install_sh_PID=$!
+#       echo "install.log will be displayed after success or failure"
+#       while ps -p $install_sh_PID > /dev/null; do
+#         echo "Still working on installing opencoarrays and dependencies"
+#         sleep 300 # prevent Travis-CI abort due to inactivity and excessive logging
+#       done
+#     else
+#       mkdir cmake-build
+#       cd cmake-build
+#       cmake -DCMAKE_INSTALL_PREFIX:PATH="$HOME/OpenCoarrays" -DCMAKE_BUILD_TYPE="$BUILD_TYPE" ..
+#       make -j 4
+#       ctest --verbose
+#       make install
+#       cd ..
+#     fi
