BREAKING CHANGE: expermntal fpm build/test/install
This commit
1. Removes ~4K lines of bash installation scripts.
2. Adds a much smaller, more maintainable, and more portable
   Homebrew- and fpm-based installation script that works on
   macOS, Linux, and Windows Subsystem for Linux.
3. Adds a test/ subdirectory containing Garden unit tests that
   fpm can run.
4. Moves src/tests to tests/ to prevent fpm building the CTest
   tests because of a build error due to duplicate module names.
5. Adjusts the CMake script for the new tests/ directory location.
6. Brackets the legacy GASNet and OpenSHMEM libraries with C
   preprocessor macros to prevent fpm from compiling them.
7. Adds an example/ subdirectory with simple demonstration rograms
   that fpm can run.
8. Puts fpm.toml in a new .gitignore file to prevent naive uses
   of fpm. (fpm builds work only after the new installer has been
   and the new fpm.toml file has been copied to the top level of
   the soure tree.)

diff --git a/src/script-templates/caf.in b/src/script-templates/caf.in
--- a/src/script-templates/caf.in
+++ b/src/script-templates/caf.in
@@ -8,7 +8,7 @@
 # arguments.
 #
 # Copyright (c) 2015-2022, Sourcery Institute
-# Copyright (c) 2015-2022, Archaeologic Inc.
+# Copyright (c) 2015-2022, Sourcery, Inc.
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -50,28 +50,25 @@ set -o pipefail
 #---------------------------
 # List of variables needing configuration:
 #
-# CAF_VERSION, opencoarrays_aware_compiler, Fortran_COMPILER, CAF_MODDIR,
-# CAF_MPI_Fortran_LINK_FLAGS, CAF_MPI_Fortran_COMPILE_FLAGS,
-# CAF_LIBS, THREADS_LIB, CAF_MPI_LIBS
-#
+#   CAF_VERSION
+#   Fortran_COMPILER
+#   CAF_MPI_Fortran_LINK_FLAGS
+#   CAF_MPI_Fortran_COMPILE_FLAGS
+#   CAF_LIBS, CAF_MPI_LIBS
 
 caf_version='@CAF_VERSION@' # fetched from `git describe` and/or
 # `.VERSION` file
-oca_compiler="@opencoarrays_aware_compiler@" # True for GFortran > 5.0.0
 
 # Compiler used to build OpenCoarrays; runtime must match compiler used during build
 cafc="@Fortran_COMPILER@"
-if [[ "${cafc}" == @*@ || -z "${cafc}" ]]; then
+if [[ "${cafc}" == @*@ ]]; then
   cafc=gfortran
 fi
-caf_mod_dir="@CAF_MODDIR@"    # location of extensions module, needed for non-OCA compilers
-mod_dir_flag="-I"
 
-
-# Ideally these should be absolute paths. Since they are array
-# variables multiple libs (absolute or not) can be specified provided
-# proper quoting is used, when @var@ is expanded. (i.e., expands with
-# double quotes around each library w/path to ensure proper word
+# Ideally these should be absolute paths. Because they are array
+# variables, multiple libs (absolute or not) can be specified provided
+# that proper quoting is used, when @var@ is expanded. (i.e., expands 
+# with double quotes around each library w/path to ensure proper word
 # splittling for paths with spaces) Handling of paths is complex
 # between CMake and pkg-config: pkg-config (new enough versions) will
 # theoretically expand paths with spaces escaped or the path
@@ -87,7 +84,6 @@ mpi_link_flags=(@CAF_MPI_Fortran_LINK_FLAGS@) # e.g. `pkg-config
 # --libs-only-L`
 mpi_compile_flags=(@CAF_MPI_Fortran_COMPILE_FLAGS@)
 caf_libs=(@CAF_LIBS@) # e.g. "libcaf_mpi" "libcaf_extensions",
-threads_lib=@THREADS_LIB@ # pthreads or compatible, needed for windows
 # preferably full paths, but could be
 # combination of -L... and -lcaf_mpi...
 mpi_libs=(@CAF_MPI_LIBS@) # e.g. `pkg-config --libs-only-l` or full paths
@@ -207,16 +203,8 @@ substitute_lib () {
   fi
 }
 
-# Always make extensions module available, user can choose whether to `use` it or not
-caf_pre_flags=("${mod_dir_flag}${prefix%/}/${caf_mod_dir}")
+caf_pre_flags=('-fcoarray=lib')
 
-if [[ "${oca_compiler}" == true ]]; then
-  if [[ -z "${caf_pre_flags[*]:-}" ]]; then
-    caf_pre_flags=('-fcoarray=lib')
-  else
-    caf_pre_flags+=('-fcoarray=lib')
-  fi
-fi
 if [[ -n "${mpi_compile_flags[*]:-}" ]]; then
   for compileflag in "${mpi_compile_flags[@]:-}"; do
       caf_pre_flags+=("${compileflag}")
@@ -236,11 +224,6 @@ if [[ -n "${caf_libs[*]:-}" ]]; then
     caf_added_libs+=("$(substitute_lib "${prefix%/}/${lib}")")
   done
 fi
-
-if [[ -n "${threads_lib}" ]]; then
-  caf_added_libs+=("${threads_lib}")
-fi
-
 if [[ -n "${mpi_libs[*]:-}" ]]; then
   for lib in "${mpi_libs[@]:-}"; do
     caf_added_libs+=("$(substitute_lib "${lib}")")
@@ -266,34 +249,10 @@ usage() {
   echo "   ${cmd} --help"
   echo "   ${cmd} -s"
   echo ""
-  echo "OpenCoarrays ${caf_version} ${cmd} supports three categories of compilers"
-  echo "with the following restrictions for each use case:"
-  echo ""
-  echo " 1. With an OpenCoarrays-Aware (OCA) compiler (GNU 5.1.0 or later),"
-  echo "   a. If any of the options listed above appear, any remaining arguments are ignored."
-  echo "   b. If present, any Fortran <source-file(s)> must have a name of the form:"
-  echo "      *.f90, *.F90, *.f, or *.F. "
-  echo ""
-  echo " 2. With non-OCA CAF compilers (Intel or Cray),"
-  echo "   a. Observe restrictions 1a-d above."
-  echo "   b. Access OpenCoarrays collective subroutines via use association with an only clause,"
-  echo "      e.g., 'use opencoarrays, only : co_sum,co_broadcast' "
-  echo ""
-  echo " 3. With non-CAF compilers (all compilers not named above),"
-  echo "   a. Observe restrictions 1a-d above."
-  echo "   b. Access OpenCoarrays capabilities via use association ('use opencoarrays')."
-  echo "   c. The only CAF statements or expressions allowed are the following:"
-  echo "      * 'num_images()' "
-  echo "      * 'this_image()' with or without arguments"
-  echo "      * 'sync all' with or without arguments."
-  echo "      * 'sync images' with or without arguments."
-  echo "      * 'error stop' without arguments."
-  echo "      * 'co_sum', 'co_broadcast', 'co_max', 'co_min', or 'co_reduce'"
-  echo ""
-  echo " The caf wrapper will append -L..., -l..., and other required flags as necessary"
-  echo " to link against OpenCoarrays, using values that get set during the OpenCoarrays"
-  echo " build and installation."
-  echo ""
+  echo "OpenCoarrays ${caf_version} ${cmd} provides a runtime library for parallel features of Fortran 2018."
+  echo "An OpenCoarrays installation includes the opencoarrays library, the caf compiler wrapper, and the cafrun."
+  echo "program launcher.  The caf wrapper invokes the compiler with the flags required to link against"
+  echo "OpenCoarrays, using values that get set during the OpenCoarrays build and installation."
 }
 
 # Print useage information if caf is invoked without arguments
@@ -340,21 +299,6 @@ elif [[ ${1} == '-h' || ${1} == '--help' ]]; then
   # Print usage information
   usage | ${PAGER:-less -i -F -X -M -J}
   exit 0
-elif [[ "${oca_compiler:-}" != "true" ]]; then
-  # Transform file(s) with the .f90, .F90, .f, or .F extension, if present:
-  # Loop over all arguments and perform simple search & replace source transformation on any Fortran sources
-  i=0
-  for arg in "${@}"; do
-    src_extension="${arg##*.}"
-    ((i+=1)) # Increment i to keep track of which arg we're processing
-    if [[ "${src_extension}" == [fF]90 || "${src_extension}" == [fF] ]]; then
-      # Edit & copy the source to replace CAF syntax with calls to public procedures in opencoarrays.f90:
-      sed -e 's/sync all/call sync_all/g' -e 's/error stop/call error_stop/g' \
-        -e 's/sync images/call sync_images/g' "${arg}" >"caf-${arg}"
-      # Replace the file name in command-line argment $i with the new name before invoking the compiler:
-      set -- "${@:1:$((i - 1))}" "caf-${arg}" "${@:$((i + 1)):$((${#} - i))}"
-    fi
-  done
 fi
 
 # Invoke the compiler along with all command-line arguments:
@@ -376,7 +320,7 @@ if "${cafc}" "${compiler_args[@]}" ; then
   exit $?
 else
   return_code=$?
-  echo "Error: command:" >&2
+  echo "Error: comand:" >&2
   echo "   \`${cafc} ${compiler_args[*]}\`" >&2
   echo "failed to compile." >&2
   exit "${return_code}"
